### ISSUE TITLE
MQTT broker

### ISSUE THREAD

**Issue by jruibarroso** [njanik/hayward-pool-heater-mqtt#1]
Hi, 
I'm trying to put this in to work , on my Hayward Pool Heater, but some doubts are present

I use as MQTT broker, my Home Assistant with IP 192.168.0.106 and it needs MQTT authentication (USER and PASS). How can I add it on *.ino ?

Thanks

**Comment by njanik** [comment]
Hi, 
You can edit the file `my_config.h` in this repo, change the username, the password, and the IP of the mqtt broker just before compiling the sketch.
