### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by sh00t2kill** [njanik/hayward-pool-heater-mqtt#10]
I have what appears to be the same board in my pool heater, so I am keen to give this a go.

Are you able to please provide a wiring diagram of how it should all be connected? Im a little confused as to what goes where!

Thanks!

**Comment by jruibarroso** [comment]
send a photo of your board

**Comment by sh00t2kill** [comment]
Will do tomorrow!
I'm more confused about what goes where on the d1 and the level shifter.

**Comment by jruibarroso** [comment]
No need of level shifter
Enviado pelo meu iPhone XX



sh00t2kill ***@***.***> escreveu em qui., 21/09/2023 às 10:04
:

**Comment by sh00t2kill** [comment]
So the logic level converter isn't required?

**Comment by jruibarroso** [comment]
No. Got mine working 100% directly connected to Hayward logic board
Enviado pelo meu iPhone XX



sh00t2kill ***@***.***> escreveu em qui., 21/09/2023 às 12:45
:

**Comment by sh00t2kill** [comment]
So I can just connect the NET port to D5, and power the board through whatever means?

**Comment by njanik** [comment]
Maybe there are multiple board revisions. On mine, I confirm that without the logic shifter, I could read the data but not "send" command.

**Comment by njanik** [comment]
> So I can just connect the NET port to D5, and power the board through whatever means?

You can follow this diagram made by a user of this repo.
https://domotic-hobby.com/tutorial-3-hayward-pool-heater-control

**Comment by sh00t2kill** [comment]
That's great! And exactly what I am looking for.

**Comment by sh00t2kill** [comment]
And its working!

Thanks for the diagram link that really helped.

I have it working and integrated with Home Assistant via mqtt.

You can add Oasis x19/24 to the list of heaters. Very common model in Australia.
