### ISSUE TITLE
A different protocol?

### ISSUE THREAD

**Issue by raomin** [njanik/hayward-pool-heater-mqtt#13]
Hello @njanik,

I just got an old heat pump from LeBonCoin ;).
It's a Mono 20P. looks pretty similar to a PC1000 board.
![image](https://github.com/njanik/hayward-pool-heater-mqtt/assets/4460208/8d7ec918-2aa8-4c7b-a6d9-2242b354dd99)

I ported the code for esp32-c3 and got only invalid frames, with irregular values.
I plugged my logic analyzer to NET and there are some significant differences with the protocol you describe in that Arduino Forum.

Start of frame is similar:
![image](https://github.com/njanik/hayward-pool-heater-mqtt/assets/4460208/63101b82-398b-4074-83cf-475f0532a595)

Then end of frame however is different from what you describe

> Par contre, chaque fin de frame est suivit d'un silence à l'état HIGH de 125 ms ou de 1s.
> Le silence est suivi d'un LOW de 9ms.

![image](https://github.com/njanik/hayward-pool-heater-mqtt/assets/4460208/a60bc1f2-28a4-4a00-8a34-e22ad986cdd7)

Here we have 5 repetitive 3ms (might be 00000) and a steady HIGH (link is pulled up).

Few frames I decoded give: 

```
New frame: 01001011011010000001010010110100111000001011000000001010001111101101001011100000
New frame: 10111011000101000001010000101000000000001100100000000000000000001110111011100000
New frame: 01001011011010000001010010110100111000001011000000001010001111101101001011100000
New frame: 10111011000101000001010000101000000000001100100000000000000000001110111011100000
New frame: 01001011011010000001010010110100111000001011000000001010001111101101001011100000
New frame: 10111011000101000001010000101000000000001100100000000000000000001110111011100000
New frame: 01001011011010000001010010110100111000001011000000001010001111101101001011100000

in HEX
0x4b6814b4e0b00a3ed2e0
0xbb14142800c80000eee0
0x4b6814b4e0b00a3ed2e0
0xbb14142800c80000eee0
0x4b6814b4e0b00a3ed2e0
0xbb14142800c80000eee0
0x4b6814b4e0b00a3ed2e0
```

I'll keep digging but I was wondering if you had an idea...

Merci d'avance! :)

**Comment by raomin** [comment]
Some patterns shows better for the ending in binary:

```
10111010111011111011111011101010101010111011101011101111101110101111111010101010111011111010101010101010111011101010111111111110111110111010111011111110101010101
11101111111011111010101110111010101010111011101010101110111010101010101010101010111110101110101010101010101010101010101010101010111111101111111011111110101010101
10111010111011111011111011101010101010111011101011101111101110101111111010101010111011111010101010101010111011101010111111111110111110111010111011111110101010101
11101111111011111010101110111010101010111011101010101110111010101010101010101010111110101110101010101010101010101010101010101010111111101111111011111110101010101
10111010111011111011111011101010101010111011101011101111101110101111111010101010111011111010101010101010111011101010111111111110111110111010111011111110101010101
11101111111011111010101110111010101010111011101010101110111010101010101010101010111110101110101010101010101010101010101010101010111111101111111011111110101010101
10111010111011111011111011101010101010111011101011101111101110101111111010101010111011111010101010101010111011101010111111111110111110111010111011111110101010101
```

**Comment by raomin** [comment]
Interestingly, half of the frames are actually two 32bit words separated by 11100000

```
01001011011010000001010010110100 11100000
10110000000010100011111011010010 11100000

101110110001010000010100001010000000000011001000000000000000000011101110 11100000

01001011011010000001010010110100 11100000
10110000000010100011111011010010 11100000

101110110001010000010100001010000000000011001000000000000000000011101110 11100000

01001011011010000001010010110100 11100000
10110000000010100011111011010010 11100000

101110110001010000010100001010000000000011001000000000000000000011101110 11100000

01001011011010000001010010110100 11100000
10110000000010100011111011010010 11100000
```
I'll program a man-in-the-middle logger and will fiddle with the controls to see the impact of the changes in the registries.
🤞

**Comment by njanik** [comment]
Indeed, it would be a completely different protocol.
It's been too long since I worked on it. I've had time to forget everything...
I mostly remember that two controllers (the touchscreen and the PC1000 card) sent information on the same pin, so there were frames that overlapped (thus completely invalid).
Is it the same thing for you?

**Comment by raomin** [comment]
Hi @njanik, I understand, time flies.
Yes, they are speaking on the same bus. 
I prepared a nice logger to log each side separately while repeating it on the other side.

If I log every state, I'll eventually figure out how the main info is encoded.

**Comment by raomin** [comment]
So I analyzed this protocol, it's indeed significantly different from yours. Overall, it's also an older version, eg the panel is not touch screen and just has a rotary and push knob.

Anyway, I forked and coded an new version to support this model. I also did some code refactoring and added few extra features (interrupt based timer, ota, Home Assistant mqtt discovery, all temperatures as sensor, etc...)
Everything works great but I ended up a bit far from your code for a simple PR plus it's not compatible with your protocol.

https://github.com/raomin/hayward-pool-heater-mqtt/tree/v2009

I doubt you would be interested into porting the changes in a PR for your repository, but if so, let me know...

**Comment by njanik** [comment]
Nice!

I've also added HA autodiscovery and OTA in the branch `feat-HA-autodiscovery`
I've tested this branch all the last summer and I think this will be the default one soon.

I understand that you've made a lot of change.
At least can you make a PR to edit the readme to add a link to your repo with the controller version ?
