### ISSUE TITLE
ESP32 compatibility

### ISSUE THREAD

**Issue by EtienneRod** [njanik/hayward-pool-heater-mqtt#14]
Hi, 

Anyone adapted this project to ESP32? 

From what I see, it should be a matter of renaming included libraries to their ESP32 counterpart and updating the pin variable with ESP32 equivalent of D5 wemos pin.

Do you think Iam missing something?

Thank You

**Comment by EtienneRod** [comment]
NVM, my board is PC1002 which is RS485

**Comment by njanik** [comment]
Hi!

I'm not 100% sure, but I don't see why it wouldn't be compatible with an ESP32 indeed. As for the PC1002 board, I'm not sure if it's compatible. Do you have a photo or a diagram to compare?

**Comment by EtienneRod** [comment]
Sorry for the delay. 

Here is the schematic of the board, as you can see, no NET only 485. I have a RS485 to wifi gateway and found some info about it, I will try to set it this summer.

The version I have don't have the wifi module documented installed. Right now there is nothing connected to CN8 and this is where I plan to install the RS485 gateway

![image](https://github.com/njanik/hayward-pool-heater-mqtt/assets/3812081/1aaeb509-8f1f-472a-9de9-a2bd1c5e2e8d)

**Comment by EtienneRod** [comment]
If anyone want to have a follow up. 

I successfully interface my heat pump with home assistant using modbus on rs485 with a wifi gateway.

more info available on home assistant forum.
https://community.home-assistant.io/t/hayward-oasis-and-other-generic-pool-heatpump-using-pc1002/733827

**Comment by njanik** [comment]
Nice! Thank you for the information for people with the PC1002 controller.
