### ISSUE TITLE
 Erreur compilation

### ISSUE THREAD

**Issue by NicolasFR64** [njanik/hayward-pool-heater-mqtt#15]
Bonjour,
total newbie, j'essaie de réaliser ce projet
Je ne connais rien au code et je n'ai jamais manipulé d'ESP8632
J'ai fait le harware (Wemos)
j'ai une erreur de compilation.
J'utilise Arduino IDE Version: 2.3.1
Une aide possible ?

C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:5:23: warning: extra tokens at end of #include directive
    5 | #include "my_config.h";
      |                       ^
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino: In function 'char* modeToString(byte)':
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:65:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   65 |         return "HEAT";
      |                ^~~~~~
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:69:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   69 |         return "COOL";
      |                ^~~~~~
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:73:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   73 |         return "AUTO";
      |                ^~~~~~
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:75:12: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   75 |     return "unknown_mode";
      |            ^~~~~~~~~~~~~~
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino: In function 'boolean mqttMsgReceivedCallBack(char*, byte*, unsigned int)':
C:\Users\capel\Downloads\hayward-poolheater-mqtt\hayward-poolheater-mqtt.ino:237:21: error: control reaches end of non-void function [-Werror=return-type]
  237 |     isProcessingCmd = false;
      |     ~~~~~~~~~~~~~~~~^~~~~~~
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: control reaches end of non-void function [-Werror=return-type]

**Comment by njanik** [comment]
Hello
Il faut installer "Arduino Core" dans l'IDE. Ensuite tu pourras modifier la board pour choisir la wemos dans l'IDE.

**Comment by NicolasFR64** [comment]
Merci !
