### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by teji24** [njanik/hayward-pool-heater-mqtt#16]
Hello,
Is this project can work on Hayward GOPAC ? the original "smart temp" wifi module don't work. (work every 20 try !!!) new app crash each time. ...
Here is a picture.
Thank you very much !
![image](https://github.com/njanik/hayward-pool-heater-mqtt/assets/13621772/825c89a7-7e79-4bf9-b150-51d12f23fe63)

**Comment by njanik** [comment]
Hello,
Sorry, I don't know. It seems, when I'm looking at the manual, that we don't have any "net" pin.  So I'm not sure without trying to capture some data from the controller board.
