### ISSUE TITLE
Error E08

### ISSUE THREAD

**Issue by mbrhe** [njanik/hayward-pool-heater-mqtt#18]
Hi,
when connecting the wemos to my pool heater from Midas i cannot get any data and get the Error EE8 on the attached pool heater display. As soon as i disconnect the wemos the error disappears.
Can you assist in resolving this issue.
The Midas pool heater uses the PC1001.
Thx

**Comment by njanik** [comment]
hello @mbrhe 

Did you use a level shifter between the PC1001 and the wemos  ?

**Comment by mbrhe** [comment]
Hey @njanik,
thanks for asking, i indeed used a level shifter during my test, but i learned that it was broken. i changed the shifter and everything is working fine.
Many thanks for your effort you put into the project.

**Comment by njanik** [comment]
@mbrhe 
No problem, glad to know you managed to make it work!
