### ISSUE TITLE
SmartTemp inventer

### ISSUE THREAD

**Issue by jerome6994** [njanik/hayward-pool-heater-mqtt#4]
hello
congratulations for this work, do you think this type of project is compatible with smart temp invent? 
do you know if there is an mqtt project that directly fetches APIs from Hayward servers?

https://www.hayward.fr/photoforum/Smartemp_Fr_GB.pdf

**Comment by njanik** [comment]
Hello! Thank you. 
No sorry, I don't know any project that fetch the Hayward api.

About the smart temp invent device: It seems that it connect directly on the same pins that I use, so I suppose that this device do exactly the same thing as my implementation.
Do you own one ?

**Comment by jerome6994** [comment]
hello Thank you for your answer
I have this heat pump with this module for 2 years.
I am reassembling this today in Jeedom.
I'm looking to move things to MQTT on the one hand and to play and discover Home Assistant too.

**Comment by njanik** [comment]
I tought this module was discontinued a long time ago. 
I don't know how you will be able to use mqtt with this module. I doubt Hayward has an "open" API.
Good luck :)

**Comment by jerome6994** [comment]
I know there is a functional plugin on jeedom but I don't know how it works
