### ISSUE TITLE
Clarify connection for level shifter/ESP/PC1000

### ISSUE THREAD

**Issue by Fabiancrg** [njanik/hayward-pool-heater-mqtt#5]
Hi,

I am interested to connect my heatpump (based on PC1000 board) but I don't understand how you connect the ESP, the level shifter and the PC1000 together.

I see on the schematic that the PC1000 has a 12V pin and you say the NET is 5V.
As we Wemos D1 is a 3.3 V logic level, we have to connect the level shifter.
I already used that and I know I have to connect the Wemos on the low level side, so VCC (3.3V), GND and the signal pin.
But for the high level, we have the NET pin at 5V, the GND but where do you get the 5V VCC ?

Could you please clarify the connections you made ?

Thank you

**Comment by njanik** [comment]
Hello, yes indeed, I did not specify this part, but in fact my wemos is located a few meters from the heat pump in my shed. So here I am using a 5v phone adapter plug.

Otherwise you could use a  mini dc dc step down 5v convertor I guess plugged to the 12v power line.

Have a good day!

**Comment by Fabiancrg** [comment]
Perfect, thank you !
