### ISSUE TITLE
Problème commande pompe

### ISSUE THREAD

**Issue by adrienyhuel** [njanik/hayward-pool-heater-mqtt#9]
Bonjour,

Le contrôleur (LCD) de ma pompe (Powerline 81521, carte PC1000 selon la doc) venant de griller (corrosion), je suis tombé par hasard sur ce projet.

Ayant un Arduino pour tester, j'ai modifié ton programme (suppression wifi et mqtt), et j'ai relié l'Arduino à la place du contrôleur.

Je reçoit bien les paramètres de la pompe, mais elle est en mode "Cool".

Je peux changer la température de consigne correctement, mais si j'essaye d'envoyer les commandes pour changer le mode ou éteindre la pompe, cela ne change rien.

Cela pourrait-il venir du fait que j'utilise un Arduino et pas un ESP ?

**Comment by njanik** [comment]
Bonjour
Quel arduino utilises tu ?
Les pins de data utilisent bien du 5v et non du 3.3v ?

**Comment by adrienyhuel** [comment]
J'utilise un Arduino Uno R3 classique, en 5V.

Ce que je trouve bizarre, c'est que je peux changer le température de consigne en envoyant la commande, cela fonctionne bien (j'ai le log "PROG TEMP" qui change bien.

Par contre, les commandes pour l'allumage/extinction ou le changement de mode n'ont aucun effet.

**Comment by njanik** [comment]
Je ne pense pas que cela puisse venir du contrôleur que tu utilises (arduino vs esp)
Malheureusement je n'ai pas d'idée... le fait que tu ne puisses plus utiliser l'écran t'empêche de pouvoir capturer la trame de changement de mode pour comparer avec celle que tu envois via l'arduino... 

Peut être que le protocol est différent (mais tu arrives pourtant a changer la température) => firmware différent ?
Carte PC1000 endommagé  par la corrosion également ?

:(

**Comment by adrienyhuel** [comment]
Je n'ai pas ouvert la pompe pour vérifier le modèle de la carte, je le ferai prochainement.

La pompe a bien fonctionné la saison dernière, et là au démarrage l'écran en s'allumait pas. En ouvrant le boitier, j'ai vu un nid de fourmis dedans, et de la corrosion

**Comment by njanik** [comment]
Ha d'accord. Bon courage en tout cas.

**Comment by adrienyhuel** [comment]
Pour infos, la carte LCD porte les références :
MXL003-V2 / 20000-430019
Elle date de 2011

Je ne sais pas si le fait de fonctionner sans cette carte peut influer sur le fonctionnement (par ex les trames correspondant à la date/heure ne sont pas envoyées)
Sachant que dans la liste des erreurs possible, on trouve :
Problème de communication E08 Dysfonctionnement du contrôleur LED ou de la connexion PCB. Vérifier la connexion des câbles

**Comment by adrienyhuel** [comment]
@njanik 

Voici des photos de la carte à l'intérieur de la pompe, je pense que c'est bien la même que la tienne : 

![IMG_20230610_162717](https://github.com/njanik/hayward-pool-heater-mqtt/assets/14916484/026fc53f-6a14-4b03-b121-826f5cc78967)
![IMG_20230610_162659](https://github.com/njanik/hayward-pool-heater-mqtt/assets/14916484/58988c03-ab97-4d73-9982-5b9a1708d44e)

**Comment by njanik** [comment]
Effectivement, ca semble être la même.

Peut être que sans le module écran, il manque quelque chose pour que ça
fonctionne alors :(
Il faudrait capturer les trames pour essayer de comprendre ce qu'il se
passe.

**Comment by adrienyhuel** [comment]
@njanik 

Je pourrais capturer les trames provenant de la carte, mais je ne vois ni comment les décoder, ni comment comprendre si quelque chose ne va pas.

**Comment by adrienyhuel** [comment]
> @njanik 
> 
> Je pourrais capturer les trames provenant de la carte, mais je ne vois ni comment les décoder, ni comment comprendre si quelque chose ne va pas.

J'ai essayé avec un esp8266, même constat. 
Je peux setter la température de consigne, mais aucun autre paramètre
